[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/tts"
  to = "https://translate.google.com/translate_tts"
  status = 200
  force = true
  headers = {Referer = "https://translate.google.com/", User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
